[workspace]
members = [
    "./grid",
]
default-members = [
    "./grid",
]

[profile.test]
opt-level = 3

[profile.bench]
debug = true

[workspace.dependencies]

[workspace.package]
edition = "2021"
rust-version = "1.65"
authors = ["James Chacon <chacon.james@gmail.com>"]

